# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wra_auto_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 823)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 451, 400))
        self.groupBox.setStyleSheet("#groupBox{border:1px solid}")
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 431, 371))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.te_official_accounts = QtWidgets.QTextEdit(self.tab_0)
        self.te_official_accounts.setEnabled(True)
        self.te_official_accounts.setGeometry(QtCore.QRect(88, 96, 320, 121))
        self.te_official_accounts.setReadOnly(True)
        self.te_official_accounts.setObjectName("te_official_accounts")
        self.pb_add_official_accounts = QtWidgets.QPushButton(self.tab_0)
        self.pb_add_official_accounts.setGeometry(QtCore.QRect(324, 60, 40, 23))
        self.pb_add_official_accounts.setObjectName("pb_add_official_accounts")
        self.pb_add_tactic0 = QtWidgets.QPushButton(self.tab_0)
        self.pb_add_tactic0.setGeometry(QtCore.QRect(337, 320, 75, 23))
        self.pb_add_tactic0.setObjectName("pb_add_tactic0")
        self.pb_clear_official_accounts = QtWidgets.QPushButton(self.tab_0)
        self.pb_clear_official_accounts.setGeometry(QtCore.QRect(368, 60, 40, 23))
        self.pb_clear_official_accounts.setObjectName("pb_clear_official_accounts")
        self.le_concern_interval_1 = QtWidgets.QLineEdit(self.tab_0)
        self.le_concern_interval_1.setGeometry(QtCore.QRect(87, 231, 61, 20))
        self.le_concern_interval_1.setObjectName("le_concern_interval_1")
        self.le_official_account = QtWidgets.QLineEdit(self.tab_0)
        self.le_official_account.setGeometry(QtCore.QRect(88, 61, 230, 20))
        self.le_official_account.setObjectName("le_official_account")
        self.label_2 = QtWidgets.QLabel(self.tab_0)
        self.label_2.setGeometry(QtCore.QRect(23, 234, 48, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab_0)
        self.label.setGeometry(QtCore.QRect(23, 63, 36, 16))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.tab_0)
        self.label_10.setGeometry(QtCore.QRect(150, 235, 21, 16))
        self.label_10.setObjectName("label_10")
        self.le_concern_interval_2 = QtWidgets.QLineEdit(self.tab_0)
        self.le_concern_interval_2.setGeometry(QtCore.QRect(158, 231, 61, 20))
        self.le_concern_interval_2.setObjectName("le_concern_interval_2")
        self.label_14 = QtWidgets.QLabel(self.tab_0)
        self.label_14.setGeometry(QtCore.QRect(21, 266, 48, 16))
        self.label_14.setObjectName("label_14")
        self.le_tactic0_interval = QtWidgets.QLineEdit(self.tab_0)
        self.le_tactic0_interval.setGeometry(QtCore.QRect(87, 264, 30, 20))
        self.le_tactic0_interval.setObjectName("le_tactic0_interval")
        self.label_15 = QtWidgets.QLabel(self.tab_0)
        self.label_15.setGeometry(QtCore.QRect(120, 269, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("#label_15{color:red}")
        self.label_15.setObjectName("label_15")
        self.label_37 = QtWidgets.QLabel(self.tab_0)
        self.label_37.setGeometry(QtCore.QRect(24, 28, 54, 12))
        self.label_37.setObjectName("label_37")
        self.le_concern_num = QtWidgets.QLineEdit(self.tab_0)
        self.le_concern_num.setGeometry(QtCore.QRect(88, 24, 30, 20))
        self.le_concern_num.setObjectName("le_concern_num")
        self.label_38 = QtWidgets.QLabel(self.tab_0)
        self.label_38.setGeometry(QtCore.QRect(121, 28, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_38.setStyleSheet("#label_38{color:red}")
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(31, 41, 60, 16))
        self.label_3.setObjectName("label_3")
        self.le_article_read_num = QtWidgets.QLineEdit(self.tab_1)
        self.le_article_read_num.setGeometry(QtCore.QRect(110, 41, 100, 20))
        self.le_article_read_num.setObjectName("le_article_read_num")
        self.cb_if_share = QtWidgets.QCheckBox(self.tab_1)
        self.cb_if_share.setGeometry(QtCore.QRect(220, 43, 45, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_if_share.setFont(font)
        self.cb_if_share.setObjectName("cb_if_share")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(40, 98, 48, 16))
        self.label_5.setObjectName("label_5")
        self.pb_add_tactic1 = QtWidgets.QPushButton(self.tab_1)
        self.pb_add_tactic1.setGeometry(QtCore.QRect(337, 320, 75, 23))
        self.pb_add_tactic1.setObjectName("pb_add_tactic1")
        self.le_read_share_interval_1 = QtWidgets.QLineEdit(self.tab_1)
        self.le_read_share_interval_1.setGeometry(QtCore.QRect(109, 94, 61, 20))
        self.le_read_share_interval_1.setObjectName("le_read_share_interval_1")
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(172, 97, 21, 16))
        self.label_11.setObjectName("label_11")
        self.le_read_share_interval_2 = QtWidgets.QLineEdit(self.tab_1)
        self.le_read_share_interval_2.setGeometry(QtCore.QRect(180, 94, 61, 20))
        self.le_read_share_interval_2.setObjectName("le_read_share_interval_2")
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setGeometry(QtCore.QRect(39, 147, 48, 16))
        self.label_16.setObjectName("label_16")
        self.le_tactic1_interval = QtWidgets.QLineEdit(self.tab_1)
        self.le_tactic1_interval.setGeometry(QtCore.QRect(109, 145, 30, 20))
        self.le_tactic1_interval.setObjectName("le_tactic1_interval")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(55, 113, 48, 16))
        self.label_6.setObjectName("label_6")
        self.pb_add_tactic2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_add_tactic2.setGeometry(QtCore.QRect(337, 320, 75, 23))
        self.pb_add_tactic2.setObjectName("pb_add_tactic2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(55, 42, 81, 16))
        self.label_4.setObjectName("label_4")
        self.le_thumbup_interval_1 = QtWidgets.QLineEdit(self.tab_2)
        self.le_thumbup_interval_1.setGeometry(QtCore.QRect(130, 110, 61, 20))
        self.le_thumbup_interval_1.setObjectName("le_thumbup_interval_1")
        self.le_moments_swipe_num = QtWidgets.QLineEdit(self.tab_2)
        self.le_moments_swipe_num.setGeometry(QtCore.QRect(131, 40, 30, 20))
        self.le_moments_swipe_num.setObjectName("le_moments_swipe_num")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(192, 112, 21, 16))
        self.label_12.setObjectName("label_12")
        self.le_thumbup_interval_2 = QtWidgets.QLineEdit(self.tab_2)
        self.le_thumbup_interval_2.setGeometry(QtCore.QRect(200, 110, 61, 20))
        self.le_thumbup_interval_2.setObjectName("le_thumbup_interval_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(51, 152, 48, 16))
        self.label_17.setObjectName("label_17")
        self.le_tactic2_interval = QtWidgets.QLineEdit(self.tab_2)
        self.le_tactic2_interval.setGeometry(QtCore.QRect(130, 150, 30, 20))
        self.le_tactic2_interval.setObjectName("le_tactic2_interval")
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(44, 76, 71, 16))
        self.label_39.setObjectName("label_39")
        self.le_moments_thumbup_ratio = QtWidgets.QLineEdit(self.tab_2)
        self.le_moments_thumbup_ratio.setGeometry(QtCore.QRect(131, 73, 30, 20))
        self.le_moments_thumbup_ratio.setObjectName("le_moments_thumbup_ratio")
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(168, 43, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_40.setFont(font)
        self.label_40.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_40.setStyleSheet("#label_40{color:red}")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setGeometry(QtCore.QRect(167, 77, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setStyleSheet("#label_41{color:red}")
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.te_chat_objects = QtWidgets.QTextEdit(self.tab_3)
        self.te_chat_objects.setEnabled(True)
        self.te_chat_objects.setGeometry(QtCore.QRect(80, 49, 331, 71))
        self.te_chat_objects.setReadOnly(True)
        self.te_chat_objects.setObjectName("te_chat_objects")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(15, 23, 51, 16))
        self.label_7.setObjectName("label_7")
        self.le_chat_object = QtWidgets.QLineEdit(self.tab_3)
        self.le_chat_object.setGeometry(QtCore.QRect(80, 21, 170, 20))
        self.le_chat_object.setObjectName("le_chat_object")
        self.pb_add_chat_objects = QtWidgets.QPushButton(self.tab_3)
        self.pb_add_chat_objects.setGeometry(QtCore.QRect(329, 20, 40, 23))
        self.pb_add_chat_objects.setObjectName("pb_add_chat_objects")
        self.pb_add_tactic3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_add_tactic3.setGeometry(QtCore.QRect(337, 320, 75, 23))
        self.pb_add_tactic3.setObjectName("pb_add_tactic3")
        self.pb_add_msg_contents = QtWidgets.QPushButton(self.tab_3)
        self.pb_add_msg_contents.setGeometry(QtCore.QRect(328, 130, 40, 23))
        self.pb_add_msg_contents.setObjectName("pb_add_msg_contents")
        self.le_msg_content = QtWidgets.QLineEdit(self.tab_3)
        self.le_msg_content.setGeometry(QtCore.QRect(80, 131, 241, 20))
        self.le_msg_content.setObjectName("le_msg_content")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(15, 133, 51, 16))
        self.label_8.setObjectName("label_8")
        self.te_msg_contents = QtWidgets.QTextEdit(self.tab_3)
        self.te_msg_contents.setEnabled(True)
        self.te_msg_contents.setGeometry(QtCore.QRect(80, 159, 331, 91))
        self.te_msg_contents.setReadOnly(True)
        self.te_msg_contents.setObjectName("te_msg_contents")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(15, 265, 48, 16))
        self.label_9.setObjectName("label_9")
        self.le_send_msg_interval_1 = QtWidgets.QLineEdit(self.tab_3)
        self.le_send_msg_interval_1.setGeometry(QtCore.QRect(80, 261, 61, 20))
        self.le_send_msg_interval_1.setObjectName("le_send_msg_interval_1")
        self.pb_clear_chat_objects = QtWidgets.QPushButton(self.tab_3)
        self.pb_clear_chat_objects.setGeometry(QtCore.QRect(370, 20, 40, 23))
        self.pb_clear_chat_objects.setObjectName("pb_clear_chat_objects")
        self.pb_clear_msg_contents = QtWidgets.QPushButton(self.tab_3)
        self.pb_clear_msg_contents.setGeometry(QtCore.QRect(370, 130, 40, 23))
        self.pb_clear_msg_contents.setObjectName("pb_clear_msg_contents")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(142, 264, 21, 16))
        self.label_13.setObjectName("label_13")
        self.le_send_msg_interval_2 = QtWidgets.QLineEdit(self.tab_3)
        self.le_send_msg_interval_2.setGeometry(QtCore.QRect(150, 261, 61, 20))
        self.le_send_msg_interval_2.setObjectName("le_send_msg_interval_2")
        self.le_tactic3_interval = QtWidgets.QLineEdit(self.tab_3)
        self.le_tactic3_interval.setGeometry(QtCore.QRect(79, 290, 30, 20))
        self.le_tactic3_interval.setObjectName("le_tactic3_interval")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(11, 292, 48, 16))
        self.label_18.setObjectName("label_18")
        self.cb_chat_object_type = QtWidgets.QComboBox(self.tab_3)
        self.cb_chat_object_type.setGeometry(QtCore.QRect(252, 20, 70, 22))
        self.cb_chat_object_type.setObjectName("cb_chat_object_type")
        self.cb_chat_object_type.addItem("")
        self.cb_chat_object_type.addItem("")
        self.cb_chat_object_type.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 420, 870, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 20, 401, 400))
        self.groupBox_2.setStyleSheet("#groupBox_2{border:1px solid}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.te_current_tactics = QtWidgets.QTextEdit(self.groupBox_2)
        self.te_current_tactics.setEnabled(True)
        self.te_current_tactics.setGeometry(QtCore.QRect(10, 40, 380, 321))
        self.te_current_tactics.setReadOnly(True)
        self.te_current_tactics.setObjectName("te_current_tactics")
        self.pb_import_tactics = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_import_tactics.setGeometry(QtCore.QRect(264, 11, 40, 23))
        self.pb_import_tactics.setObjectName("pb_import_tactics")
        self.pb_export_tactics = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_export_tactics.setGeometry(QtCore.QRect(307, 11, 40, 23))
        self.pb_export_tactics.setObjectName("pb_export_tactics")
        self.pb_clear_tactics = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_clear_tactics.setGeometry(QtCore.QRect(349, 11, 40, 23))
        self.pb_clear_tactics.setObjectName("pb_clear_tactics")
        self.pb_start = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_start.setGeometry(QtCore.QRect(349, 370, 41, 23))
        self.pb_start.setObjectName("pb_start")
        self.cb_screen_off = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_screen_off.setGeometry(QtCore.QRect(220, 376, 71, 16))
        self.cb_screen_off.setObjectName("cb_screen_off")
        self.cb_switch_accounts = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_switch_accounts.setGeometry(QtCore.QRect(270, 376, 71, 16))
        self.cb_switch_accounts.setObjectName("cb_switch_accounts")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 434, 870, 361))
        self.groupBox_3.setStyleSheet("#groupBox_3{border:1px solid}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 850, 327))
        self.tableView.setStyleSheet("Widget{text-align:center}")
        self.tableView.setObjectName("tableView")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(470, 24, 20, 390))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微信养号"))
        self.groupBox.setTitle(_translate("MainWindow", "策略维护"))
        self.pb_add_official_accounts.setText(_translate("MainWindow", "添加"))
        self.pb_add_tactic0.setText(_translate("MainWindow", "添加策略"))
        self.pb_clear_official_accounts.setText(_translate("MainWindow", "清空"))
        self.label_2.setText(_translate("MainWindow", "间隔(秒)"))
        self.label.setText(_translate("MainWindow", "公众号"))
        self.label_10.setText(_translate("MainWindow", "-"))
        self.label_14.setText(_translate("MainWindow", "策略间隔"))
        self.label_15.setText(_translate("MainWindow", "*单位(分钟),该策略执行完成后的等待时间"))
        self.label_37.setText(_translate("MainWindow", "关注数"))
        self.label_38.setText(_translate("MainWindow", "*从维护的公众号列表中随机取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "关注公众号"))
        self.label_3.setText(_translate("MainWindow", "阅读文章数"))
        self.cb_if_share.setText(_translate("MainWindow", "转发"))
        self.label_5.setText(_translate("MainWindow", "间隔(秒)"))
        self.pb_add_tactic1.setText(_translate("MainWindow", "添加策略"))
        self.label_11.setText(_translate("MainWindow", "-"))
        self.label_16.setText(_translate("MainWindow", "策略间隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "文章阅读转发"))
        self.label_6.setText(_translate("MainWindow", "间隔(秒)"))
        self.pb_add_tactic2.setText(_translate("MainWindow", "添加策略"))
        self.label_4.setText(_translate("MainWindow", "滑动次数"))
        self.label_12.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "策略间隔"))
        self.label_39.setText(_translate("MainWindow", "点赞概率(%)"))
        self.label_40.setText(_translate("MainWindow", "*浏览朋友圈时,向下滑动的次数"))
        self.label_41.setText(_translate("MainWindow", "*浏览每条朋友圈动态时,根据概率决定是否点赞"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "朋友圈点赞"))
        self.label_7.setText(_translate("MainWindow", "聊天对象"))
        self.pb_add_chat_objects.setText(_translate("MainWindow", "添加"))
        self.pb_add_tactic3.setText(_translate("MainWindow", "添加策略"))
        self.pb_add_msg_contents.setText(_translate("MainWindow", "添加"))
        self.label_8.setText(_translate("MainWindow", "消息内容"))
        self.label_9.setText(_translate("MainWindow", "间隔(秒)"))
        self.pb_clear_chat_objects.setText(_translate("MainWindow", "清空"))
        self.pb_clear_msg_contents.setText(_translate("MainWindow", "清空"))
        self.label_13.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "策略间隔"))
        self.cb_chat_object_type.setItemText(0, _translate("MainWindow", "类型"))
        self.cb_chat_object_type.setItemText(1, _translate("MainWindow", "好友"))
        self.cb_chat_object_type.setItemText(2, _translate("MainWindow", "群聊"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "聊天消息"))
        self.groupBox_2.setTitle(_translate("MainWindow", "当前策略"))
        self.pb_import_tactics.setText(_translate("MainWindow", "导入"))
        self.pb_export_tactics.setText(_translate("MainWindow", "导出"))
        self.pb_clear_tactics.setText(_translate("MainWindow", "清空"))
        self.pb_start.setText(_translate("MainWindow", "开始"))
        self.cb_screen_off.setText(_translate("MainWindow", "熄屏"))
        self.cb_switch_accounts.setText(_translate("MainWindow", "切换账号"))
        self.groupBox_3.setTitle(_translate("MainWindow", "设备信息"))

